// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Y_5ZKmOETsu9TLrtRvM1EWUvzypV2Wc',
    appId: '1:17325984042:android:222a2c4cdea4d6afdb3653',
    messagingSenderId: '17325984042',
    projectId: 'callblackline-tse',
    databaseURL: 'https://callblackline-tse-default-rtdb.firebaseio.com',
    storageBucket: 'callblackline-tse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy3sMcLA7ngj-OZyOpaMiTv2U9aPkY-pY',
    appId: '1:17325984042:ios:9f04b128af1f6b4bdb3653',
    messagingSenderId: '17325984042',
    projectId: 'callblackline-tse',
    databaseURL: 'https://callblackline-tse-default-rtdb.firebaseio.com',
    storageBucket: 'callblackline-tse.appspot.com',
    iosClientId: '17325984042-52pfuujjtghp663p1s7uafhqfcfaat3l.apps.googleusercontent.com',
    iosBundleId: 'com.tse.cbl.callBlackLine',
  );
}
